[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<main.cpp>
  -<sd_diag.cpp>

lib_deps =
  knolleary/PubSubClient

build_flags =
  -D CORE_DEBUG_LEVEL=1


[env:sd-diagnostic]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<sd_diag.cpp>
  -<main.cpp>
build_flags =
  -D CORE_DEBUG_LEVEL=1
